-- AlterTable
ALTER TABLE "Space" ALTER COLUMN "rulesetType" SET DEFAULT 'CASUAL';

-- AlterTable
ALTER TABLE "Vessel" ADD COLUMN     "electricalHealth" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "engineHealth" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "floodingDamage" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "hullIntegrity" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "steeringHealth" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
